plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = "${neoforge_version}"

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
            dependencies {
                clientAdditionalRuntimeClasspath(serverAdditionalRuntimeClasspath('org.yaml:snakeyaml:2.0'))
            }
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    jarJar(implementation("org.yaml:snakeyaml")) {
        version {
            strictly '[2.0,3.0)'
            prefer '2.0'
        }
    }
}